### ISSUE TITLE
Unable to compile GP-GOMEA on dockerized Ubuntu

### ISSUE THREAD

**Issue by rdebokx** [marcovirgolin/GP-GOMEA#2]
Hi Marco,

First of all huge compliments on GP-GOMEA and the C++ implementation you provided. It's easy to read and well documented.

I was interested in the applicability of the algorithm and wanted to play around a bit with it to see how I could use it.
I'm personally using MacOS, so since the installation instructions were provided for Ubuntu and Fedora, I figured I'd give it a go and try to run the installation in a dockerized Ubuntu installation.

However, I ran into an issue which seems to be related to compiling the GP-GOMEA source code. Although I can easily read the code, I have very little experience with C++, so I was hoping you could help me out with the following issue.

### To Reproduce
I've cloned your repo and added a `Dockerfile` with the following contents:

```
FROM ubuntu:18.04

# Upgrade installed packages
RUN apt-get update && apt-get upgrade -y && apt-get clean

ADD . .

# Python package management and basic dependencies
RUN apt-get install -y curl python3.7 python3.7-dev python3.7-distutils

# Register the version in alternatives
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1

# Set python 3 as the default python
RUN update-alternatives --set python /usr/bin/python3.7

# Upgrade pip to latest version
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py --force-reinstall && \
    rm get-pip.py

# Install dependencies
RUN apt-get -y install g++ pkg-config libarmadillo-dev python3-dev libboost-all-dev make

# compile the c++ project
RUN echo ">>> Compiling GP-GOMEA source code..." && make

# copy the .so library into the python package
RUN cp dist/Python_Release/GNU-Linux/gpgomea pyGPGOMEA/gpgomea.so

# launch pip install
RUN echo ">>> Running pip install..." && pip3 install .

# Test the installation
RUN echo ">>> Test installation..." &&  python3 test.py

```

Next, I ran `docker build --tag gpgomea:1.0 .`, which after a while resulted in the following error:

```
...
rm -f "build/Python_Release/GNU-Linux/Utils/Logger.o.d"
g++ -fopenmp -fPIC -shared `pkg-config --cflags python3` -O2 -std=c++14   -c   -MMD -MP -MF "build/Python_Release/GNU-Linux/Utils/Logger.o.d" -o build/Python_Release/GNU-Linux/Utils/Logger.o Utils/Logger.cpp
mkdir -p build/Python_Release/GNU-Linux/Utils
rm -f "build/Python_Release/GNU-Linux/Utils/Utils.o.d"
g++ -fopenmp -fPIC -shared `pkg-config --cflags python3` -O2 -std=c++14   -c   -MMD -MP -MF "build/Python_Release/GNU-Linux/Utils/Utils.o.d" -o build/Python_Release/GNU-Linux/Utils/Utils.o Utils/Utils.cpp
Utils/Utils.cpp: In instantiation of 'static boost::python::numpy::ndarray Utils::ToNumpyArray(std::vector<_RealType>) [with T = double]':
Utils/Utils.cpp:233:47:   required from here
Utils/Utils.cpp:222:17: warning: narrowing conversion of 'vector.std::vector<double>::size()' from 'std::vector<double>::size_type {aka long unsigned int}' to 'Py_intptr_t {aka long int}' inside { } [-Wnarrowing]
     Py_intptr_t shape[1] = {vector.size()};
                 ^~~~~
mkdir -p build/Python_Release/GNU-Linux/Variation
rm -f "build/Python_Release/GNU-Linux/Variation/SubtreeVariator.o.d"
g++ -fopenmp -fPIC -shared `pkg-config --cflags python3` -O2 -std=c++14   -c   -MMD -MP -MF "build/Python_Release/GNU-Linux/Variation/SubtreeVariator.o.d" -o build/Python_Release/GNU-Linux/Variation/SubtreeVariator.o Variation/SubtreeVariator.cpp
mkdir -p build/Python_Release/GNU-Linux/Variation
rm -f "build/Python_Release/GNU-Linux/Variation/TreeInitializer.o.d"
g++ -fopenmp -fPIC -shared `pkg-config --cflags python3` -O2 -std=c++14   -c   -MMD -MP -MF "build/Python_Release/GNU-Linux/Variation/TreeInitializer.o.d" -o build/Python_Release/GNU-Linux/Variation/TreeInitializer.o Variation/TreeInitializer.cpp
mkdir -p build/Python_Release/GNU-Linux
rm -f "build/Python_Release/GNU-Linux/python_exposer.o.d"
g++ -fopenmp -fPIC -shared `pkg-config --cflags python3` -O2 -std=c++14   -c   -MMD -MP -MF "build/Python_Release/GNU-Linux/python_exposer.o.d" -o build/Python_Release/GNU-Linux/python_exposer.o python_exposer.cpp
python_exposer.cpp: In function 'void init_module_gpgomea()':
python_exposer.cpp:223:30: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     py::class_<GPGOMEA, std::auto_ptr<GPGOMEA> >("GPGOMEA", py::init<std::string>())
                              ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /usr/include/boost/function/function_base.hpp:16,
                 from /usr/include/boost/function/detail/prologue.hpp:17,
                 from /usr/include/boost/function/function_template.hpp:13,
                 from /usr/include/boost/function/detail/maybe_include.hpp:13,
                 from /usr/include/boost/function/function0.hpp:11,
                 from /usr/include/boost/python/errors.hpp:13,
                 from /usr/include/boost/python/handle.hpp:11,
                 from /usr/include/boost/python/args_fwd.hpp:10,
                 from /usr/include/boost/python/args.hpp:10,
                 from /usr/include/boost/python.hpp:11,
                 from python_exposer.cpp:6:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
mkdir -p dist/Python_Release/GNU-Linux
g++ -fopenmp -fPIC -shared `pkg-config --cflags python3` -O2 -std=c++14    -o dist/Python_Release/GNU-Linux/gpgomea build/Python_Release/GNU-Linux/Fitness/AccuracyFitness.o build/Python_Release/GNU-Linux/Fitness/PythonFitness.o build/Python_Release/GNU-Linux/main.o build/Python_Release/GNU-Linux/Evolution/EvolutionRun.o build/Python_Release/GNU-Linux/Evolution/EvolutionState.o build/Python_Release/GNU-Linux/Evolution/GenerationHandler.o build/Python_Release/GNU-Linux/Evolution/PopulationInitializer.o build/Python_Release/GNU-Linux/Fitness/Fitness.o build/Python_Release/GNU-Linux/Fitness/SymbolicRegressionFitness.o build/Python_Release/GNU-Linux/Fitness/SymbolicRegressionLinearScalingFitness.o build/Python_Release/GNU-Linux/GOMEA/GOMEAFOS.o build/Python_Release/GNU-Linux/GOMEA/GOMEAGenerationHandler.o build/Python_Release/GNU-Linux/GOMEA/GOMEATreeInitializer.o build/Python_Release/GNU-Linux/GOMEA/GOMVariator.o build/Python_Release/GNU-Linux/Genotype/Node.o build/Python_Release/GNU-Linux/Operators/Operator.o build/Python_Release/GNU-Linux/RunHandling/IMSHandler.o build/Python_Release/GNU-Linux/Selection/TournamentSelection.o build/Python_Release/GNU-Linux/Semantics/SemanticBackpropagator.o build/Python_Release/GNU-Linux/Semantics/SemanticLibrary.o build/Python_Release/GNU-Linux/Utils/KDTree.o build/Python_Release/GNU-Linux/Utils/Logger.o build/Python_Release/GNU-Linux/Utils/Utils.o build/Python_Release/GNU-Linux/Variation/SubtreeVariator.o build/Python_Release/GNU-Linux/Variation/TreeInitializer.o build/Python_Release/GNU-Linux/python_exposer.o `pkg-config --libs python3` -larmadillo -lboost_program_options -lboost_system -lboost_python37 -lboost_numpy37 
/usr/bin/ld: cannot find -lboost_python37
/usr/bin/ld: cannot find -lboost_numpy37
collect2: error: ld returned 1 exit status
Makefile-Python_Release.mk:82: recipe for target 'dist/Python_Release/GNU-Linux/gpgomea' failed
make[2]: Leaving directory '/'
make[2]: *** [dist/Python_Release/GNU-Linux/gpgomea] Error 1
Makefile-Python_Release.mk:79: recipe for target '.build-conf' failed
make[1]: Leaving directory '/'
make[1]: *** [.build-conf] Error 2
Makefile-impl.mk:37: recipe for target '.build-impl' failed
make: *** [.build-impl] Error 2
The command '/bin/sh -c echo ">>> Compiling GP-GOMEA source code..." && make' returned a non-zero code: 2
```

I've added the full log as attachment.
Do you know what could be the problem?
[log.txt](https://github.com/marcovirgolin/GP-GOMEA/files/5616732/log.txt)

**Comment by marcovirgolin** [comment]
Hi, thanks so much for your kind words. 
Sorry about the fact that it is not macOS friendly. I actually welcome any help in making this repo better.

The good news is that it compiled everything, the issue is with linking. Specifically:
/usr/bin/ld: cannot find -lboost_python37
/usr/bin/ld: cannot find -lboost_numpy37

Are you sure that your boost installation is relying on python3.7? 
If it is using 3.8, simply replace "37" with "38", it should work just fine.

**Comment by rdebokx** [comment]
Thanks @marcovirgolin ! It turns out indeed that somehow, `python3` got linked to version `3.6.9`.
I'll give it a try tomorrow to see how I can link it to either 3.7 or 3.8.

I'll keep you posted, hopefully I can contribute the findings to this repository.

**Comment by rdebokx** [comment]
Hi @marcovirgolin , 

I gave it another try this morning. I managed to resolve the issue where `python3` was still pointing to python `3.6.9`.
Now both `python` and `python3` point to `3.7.5`.

Nonetheless, the issues remain. Do you think there is some way to check whether all the required dependencies are installed?

I've attached my latest version of the Dockerfile below, as well as the logs
[log2.txt](https://github.com/marcovirgolin/GP-GOMEA/files/5621618/log2.txt)

```
FROM ubuntu:18.04

# Upgrade installed packages
RUN apt-get update && apt-get upgrade -y && apt-get clean

ADD . .

# Python package management and basic dependencies
RUN apt-get install -y curl python3.7 python3.7-dev python3.7-distutils

# Register the version in alternatives
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1

# Set python 3 as the default python and python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 #TODO: remove?
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2

RUN rm /usr/bin/python3
RUN ln -s python3.7 /usr/bin/python3

# Upgrade pip to latest version
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py --force-reinstall && \
    rm get-pip.py

# Install dependencies
RUN apt-get -y install g++ pkg-config libarmadillo-dev libboost-all-dev make

# compile the c++ project
RUN python --version
RUN python3 --version
RUN echo ">>> Compiling GP-GOMEA source code..." && make

# copy the .so library into the python package
RUN cp dist/Python_Release/GNU-Linux/gpgomea pyGPGOMEA/gpgomea.so

# launch pip install
RUN echo ">>> Running pip install..." && pip install .

# Test the installation
RUN echo ">>> Test installation..." &&  python test.py
```

**Comment by marcovirgolin** [comment]
Looking at the logs, the problem is the same as before.

Probably, your boost thinks it should use an earlier version of python. 
Often, Ubuntu's repos are a bit old, and it could be that your version of boost does not support python3.7.

I suggest you:
1- uninstall your boost installation
2- download a recent version of boost from here: https://www.boost.org/users/download/ 
3- set up user-config.jam to use python3.7: https://www.boost.org/doc/libs/1_68_0/libs/python/doc/html/building/configuring_boost_build.html
4- install boost (their instructions are pretty neat)

**Comment by rdebokx** [comment]
Thanks @marcovirgolin ! I'll give this a try in the coming week.

**Comment by rdebokx** [comment]
Hi Marco,

Due to some busy days at work, it took a while before I got to it, but I finally got some progress.
It now reinstalls the latest version of boost, but somehow still has some issues with linking to numpy37
Is the linking of these somehow related, or are they two separate processes? Also wondering if you've seen this issue before.
Another thing I thought of: which version of Ubuntu have you tested this on? The Docker container I'm building is using 18.04, but if you have this running on a different version, I'd gladly switch to that same version.

Below is the log and the updated Dockerfile. Please let me know what you think.

[log.txt](https://github.com/marcovirgolin/GP-GOMEA/files/5709990/log.txt)


```
FROM ubuntu:18.04

# Upgrade installed packages
RUN apt-get update && apt-get upgrade -y && apt-get clean

ADD . .

# Python package management and basic dependencies
RUN apt-get install -y curl python3.7 python3-dev python3.7-dev python3.7-distutils

# Register the version in alternatives
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1

RUN rm /usr/bin/python3
RUN ln -s python3.7 /usr/bin/python3

# Upgrade pip to latest version
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py --force-reinstall && \
    rm get-pip.py

# Install dependencies
RUN apt-get -y install g++ pkg-config libarmadillo-dev make build-essential autotools-dev libicu-dev libbz2-dev wget #libboost-all-dev

# Install latest boost version
RUN apt-get -y --purge remove libboost-all-dev libboost-doc libboost-dev && rm -f /usr/lib/libboost_*
RUN wget https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 && \
    tar --bzip2 -xf boost_1_75_0.tar.bz2 && \
    cd boost_1_75_0 && \
    # this will generate ./b2
    ./bootstrap.sh  && \
    ./b2 --with=all install

# compile the c++ project
# TODO: remove these
RUN python --version
RUN python3 --version
RUN pkg-config --variable pc_path pkg-config
RUN ls /usr/lib/pkgconfig
RUN ls /usr/share/pkgconfig

RUN echo ">>> Compiling GP-GOMEA source code..." && make

# copy the .so library into the python package
RUN cp dist/Python_Release/GNU-Linux/gpgomea pyGPGOMEA/gpgomea.so

# launch pip install
RUN echo ">>> Running pip install..." && pip install .

# Test the installation
RUN echo ">>> Test installation..." &&  python test.py
```

**Comment by marcovirgolin** [comment]
To answer your question, I believe I also used 18.04. But actually, it's all about the version of boost and what version of python boost expects (or so I think :) )

Your install script looks okay to me, but, as I mentioned, IDK what is the version of python that boost expects.
Can you please take a look at boost's user-config.yaml file prior to installation, and set it to use python 3.7? (or whatever version that is then expected by GP-GOMEA for the respective libraries of boost python and boost numpy, which you can change in GP-GOMEA's Makefile-variables.mk).

Take a look at this:
https://github.com/boostorg/python/issues/215


Alternatively, you could see what version the boost libraries for python and numpy are getting installed (look for libboost_python* and libboost_numpy*), e.g., maybe they are at 3.8 by default; then you can change GP-GOMEA's Makefile-variables.mk to point to that version. I think that my code should work with any python 3.6+

**Comment by rdebokx** [comment]
Thanks again for all the help!

Should the file be named `user-config.jam` or `user-config.yaml`? 
I previously created `user-config.jam` as you suggested (and as documented in the link) with the following contents: 
```
using python : 3.7 ;
```
I renamed it to `user-config.yaml`, but this resulted in the same errors.

`Makefile-variables.mk` contains the original configuration: 
```
# PYTHON LIB VERSIONS
PYTHON_VERSION=python3
LIB_BOOST_PYTHON=-lboost_python37
LIB_BOOST_NUMPY=-lboost_numpy37
```

Both `RUN python --version` and `RUN python3 --version` (executed inside the Docker container when building the docker image) return `Python 3.7.5`

Any reference to `libboost_puthon*` in the logs all end at `37` (eg. `libboost_python37.so.1.75.0` or `libboost_python-variant-shared-py3.7.cmake`)

So it seems that everything pointing to python 3.7 I think? Do you think it might be worth the effort trying to switch all of this to python 3.8?

Thanks again!

**Comment by marcovirgolin** [comment]
It seems to me it should be **.jam**: https://github.com/boostorg/boost/search?q=user-config 

3.7 is fine, no need to try to have 3.8. 

You do not mention a **libboost_numpy37**, which is the one that is missing for the linking process of GP-GOMEA. Can you check that that library is actually being generated when installing boost? It should o.o

**Comment by rdebokx** [comment]
Good to hear that the `.jam` extension was correct and that 3.8 is not needed :) 

You made a good point that I didn't mention `libboost_numpy37`. I checked the logs and in fact, it's doesn't occur in the logs!

I investigated a bit if and where it is installed any why `ld` didn't find it. After some hours I got stuck on the following:

- As mentioned, `libboost_numpy37` does not occur anywhere in the logs when installing boost. However, if I run `find / -name "numpy.hpp"` in the container, it results in:
```
/usr/local/include/boost/python/numpy.hpp
/boost_1_75_0/boost/python/numpy.hpp
```

- I managed to reproduce the behavior / error also by running `ld -lboost_numpy37 --verbose` in the container. The output is attached in the log file, but it ends with the following:

```
==================================================
attempt to open //usr/local/lib/x86_64-linux-gnu/libboost_numpy37.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libboost_numpy37.a failed
attempt to open //lib/x86_64-linux-gnu/libboost_numpy37.so failed
attempt to open //lib/x86_64-linux-gnu/libboost_numpy37.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libboost_numpy37.so failed
attempt to open //usr/lib/x86_64-linux-gnu/libboost_numpy37.a failed
attempt to open //usr/lib/x86_64-linux-gnu64/libboost_numpy37.so failed
attempt to open //usr/lib/x86_64-linux-gnu64/libboost_numpy37.a failed
attempt to open //usr/local/lib64/libboost_numpy37.so failed
attempt to open //usr/local/lib64/libboost_numpy37.a failed
attempt to open //lib64/libboost_numpy37.so failed
attempt to open //lib64/libboost_numpy37.a failed
attempt to open //usr/lib64/libboost_numpy37.so failed
attempt to open //usr/lib64/libboost_numpy37.a failed
attempt to open //usr/local/lib/libboost_numpy37.so failed
attempt to open //usr/local/lib/libboost_numpy37.a failed
attempt to open //lib/libboost_numpy37.so failed
attempt to open //lib/libboost_numpy37.a failed
attempt to open //usr/lib/libboost_numpy37.so failed
attempt to open //usr/lib/libboost_numpy37.a failed
attempt to open //usr/x86_64-linux-gnu/lib64/libboost_numpy37.so failed
attempt to open //usr/x86_64-linux-gnu/lib64/libboost_numpy37.a failed
attempt to open //usr/x86_64-linux-gnu/lib/libboost_numpy37.so failed
attempt to open //usr/x86_64-linux-gnu/lib/libboost_numpy37.a failed
The command '/bin/sh -c ld -lboost_numpy37 --verbose' returned a non-zero code: 1
```

[log.txt](https://github.com/marcovirgolin/GP-GOMEA/files/5771282/log.txt)

I don't have a lot of knowledge about `ld` or `libboost`, but the options I'm considering:

- Option A: install the right `libboost_numpy37.so` at one of the expected locations, but how to do this? It seems not the same as the .hpp file.
- Option B: Provide a pointer to the boost path to the compiler, like described here: https://stackoverflow.com/a/16710346, but where is the compiler called?

Which of these options do you think is best and can you help me out with some pointers there? Thanks again!

**Comment by marcovirgolin** [comment]
Hi,

This is really strange, `libboost_numpy37` should be at the same location of `libboost_python37`, so (1) you should be able to find it there; (2) if `libboost_python37` is in the path (and it seems to me the linker of GP-GOMEA finds it, right?), so should be `libboost_numpy37`. 

Indeed, the `.hpp` file is something else, do not worry about that.

I checked my installation and I'm using boost 1.71.0 (dev). 
I think Ubuntu 20.04 comes already with that. I mean, if you run `sudo apt install libboost-all-dev`, you should get it (perhaps even with python 3.8).  

Anyway, installing from https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 as you do should work, I think. I really do not know why your installation is not producing the boost numpy library. 
At this point, perhaps you can try to open an issue in the boost repo, asking why `libboost_python37` is generated but `libboost_numpy37.so` is not. I am sorry I could not figure this out for you.

**Comment by rdebokx** [comment]
Hi Marco,

No worries at all. I very much appreciate the time and effort you've put
into this so far.
In a way it's good to hear that I at least exhausted the possibilities,
although it's really to bad I didn't get it working.
I'll try to submit an issue in the boos repo somewhere in the next days
with a minimal case to reproduce this issue and will link it here.

Thanks again!

Op do 7 jan. 2021 om 12:00 schreef Marco <notifications@github.com>:

**Comment by rdebokx** [comment]
Hi @marcovirgolin 
I'm happy to announce that, with some help of the members of the Boost mailing list, I was able to get it working.
Let me know what you think of #6
