### ISSUE TITLE
add include path to Makefile

### ISSUE THREAD

**Issue by lacava** [marcovirgolin/GP-GOMEA#3]
hi @marcovirgolin ! working on installing this within a conda environment. To do so I just need to add a customized include path to the flags during compilation (`-I $CONDA_PATH`). I'm not sure which Makefile to add this to during installation. Thanks in advance!

**Comment by marcovirgolin** [comment]
Hi there! 
I think line 70 of Makefile-Python_Release.mk should work, let me know.

**Comment by lacava** [comment]
that worked thank you!
