### ISSUE TITLE
install without sudo 

### ISSUE THREAD

**Issue by lacava** [marcovirgolin/GP-GOMEA#8]
hey Marco, I was wondering if you could help figure out how to install GP-GOMEA without `sudo`, as mentioned in this issue: https://github.com/EpistasisLab/srbench/issues/21

thanks!

**Comment by marcovirgolin** [comment]
Hi Bill, as far as I can see there's no need to use sudo when calling make. You may need sudo to install other dependencies (e.g., boost, armadillo) natively i.e. as opposed to on a virtual environment. 
Can you try to remove "sudo" and see if it works also for you? If it does not, can you let me know what the error log is?

**Comment by lacava** [comment]
yep, you're right, can't remember why i added it in the first place. thanks!
